### ISSUE TITLE
FYI: I published a Deno version

### ISSUE THREAD

**Issue by oguimbal** [no-context/moo#148]
Hi,

FYI, I published [a Deno version of moo](https://deno.land/x/moo@0.5.1.1)

Let me know if you have any problem with that, or comment.

**Comment by rethab** [comment]
Hey @oguimbal, did you publish it from a fork? I couldn't find that repository under your handle..

Anyways, I had some issues using the deno version. I have tried this:

```deno
import * as moo from "https://deno.land/x/moo@0.5.1-deno.2/mod.ts";

moo.states({})
```

but I get:

```text
error: Uncaught TypeError: moo.states is not a function
moo.states({})
```

Someone at the [deno discord](https://discord.com/channels/684898665143206084/689420767620104201/1014556126609674271) pointed out that the .js and .d.ts were out of sync. How are you using this module?

Using `compileStates` seems to work with deno 1.25.0, but the [intellij plugin](https://plugins.jetbrains.com/plugin/14382-deno) complains about it.
